const API = 'http://localhost:5001/api';
const token = () => localStorage.getItem('campusfix_admin_token');
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const request = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { ...options, headers: {'Content-Type':'application/json', ...(options.headers || {}), ...(token() ? {'Authorization': `Bearer ${token()}`} : {})} }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; };

if (document.getElementById('ticketRows') && !token()) location.replace('login.html');

const loginForm = document.getElementById('adminLoginForm');
if (loginForm) {
  document.getElementById('showRegister').onclick = () => { document.getElementById('adminRegisterForm').hidden = false; document.getElementById('showRegister').hidden = true; };
  loginForm.onsubmit = async event => { event.preventDefault(); try { const data = await request('/admin/login', {method:'POST', body:JSON.stringify({email:adminEmail.value,password:adminPassword.value})}); localStorage.setItem('campusfix_admin_token', data.token); localStorage.setItem('campusfix_admin', JSON.stringify(data.admin)); location.href='dashboard.html'; } catch (error) { adminMessage.textContent = error.message; } };
  document.getElementById('adminRegisterForm').onsubmit = async event => { event.preventDefault(); try { await request('/admin/register', {method:'POST', body:JSON.stringify({name:adminName.value,email:adminEmail.value,password:adminPassword.value,registration_code:adminCode.value})}); adminMessage.textContent='Account created. Sign in above.'; } catch (error) { adminMessage.textContent = error.message; } };
}

const rows = document.getElementById('ticketRows');
if (rows) {
  const renderStats = data => { adminStats.innerHTML = [['Total Users',data.total_users],['Students',data.students],['Employees',data.employees],['Total Tickets',data.total],['Open Tickets',data.open],['In Progress',data.in_progress],['Resolved',data.resolved],['High Priority',data.high_priority]].map(item => `<div class="admin-stat">${item[0]}<b>${item[1]}</b></div>`).join(''); };
  const renderUsers = users => { userRows.innerHTML = users.map(user => `<tr><td>${esc(user.username || `${user.firstName || ''} ${user.lastName || ''}`)}</td><td>${esc(user.usertype)}</td><td>${esc(user.registration_number || user.employee_id || '')}</td><td>${esc(user.email)}</td><td>${esc(user.department || '')}</td></tr>`).join('') || '<tr><td colspan="5">No users found.</td></tr>'; };
  const load = async () => { try { const [stats, listing, users] = await Promise.all([request('/admin/stats'), request(`/admin/tickets?search=${encodeURIComponent(ticketSearch.value)}`), request('/admin/users')]); renderStats(stats); renderUsers(users.users); rows.innerHTML = listing.tickets.map(ticket => `<tr><td>${esc(ticket.ticket_id)}</td><td>${esc(ticket.username)}</td><td>${esc(ticket.issue)}</td><td>${esc(ticket.category)}</td><td>${esc(ticket.priority)}</td><td>${esc(ticket.assigned_team || ticket.department)}</td><td>${esc(ticket.status)}</td><td>${esc(new Date(ticket.created_at).toLocaleDateString())}</td><td><button class="table-action" data-id="${esc(ticket.ticket_id)}">View</button></td></tr>`).join('') || '<tr><td colspan="9">No tickets found.</td></tr>'; rows.querySelectorAll('[data-id]').forEach(button => button.onclick = () => showDetail(button.dataset.id)); } catch (error) { rows.innerHTML = `<tr><td colspan="9">${esc(error.message)}</td></tr>`; } };
  const showDetail = async id => { try { const data = await request(`/admin/tickets/${encodeURIComponent(id)}`); const ticket = data.ticket; ticketDetail.hidden = false; ticketDetail.innerHTML = `<div class="admin-detail"><h2>${esc(ticket.ticket_id)}</h2><p>${esc(ticket.issue)} | ${esc(ticket.username)} | ${esc(ticket.user_type || ticket.usertype)}</p><div class="admin-detail-grid"><label>Status<select id="editStatus"><option>open</option><option>assigned</option><option>in_progress</option><option>waiting_for_user</option><option>resolved</option><option>closed</option></select></label><label>Priority<select id="editPriority"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Team<select id="editTeam"><option>Network Support</option><option>Hardware Support</option><option>Software Support</option><option>Account Support</option><option>General IT Support</option></select></label></div><p><strong>AI Summary:</strong> ${esc(ticket.ai_summary)}</p><p><strong>Timeline:</strong> ${esc((ticket.timeline || []).map(item => item.event).join(' | '))}</p><textarea id="editNote" placeholder="Add an admin note"></textarea><button class="admin-primary" id="saveTicket">Save Ticket</button></div>`; editStatus.value=ticket.status; editPriority.value=ticket.priority; editTeam.value=ticket.assigned_team || ticket.department; saveTicket.onclick=async()=>{await request(`/admin/tickets/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:editStatus.value,priority:editPriority.value,assigned_team:editTeam.value,note:editNote.value})}); await load(); await showDetail(id);}; } catch(error) { ticketDetail.innerHTML=`<p>${esc(error.message)}</p>`; } };
  ticketSearch.oninput = load; adminNameDisplay.textContent = JSON.parse(localStorage.getItem('campusfix_admin') || '{}').name || 'Administrator'; adminLogout.onclick=()=>{localStorage.removeItem('campusfix_admin_token');location.href='login.html';}; load();
}
